"""The published contract, checked for the things that only break somewhere else.

`backend/openapi.json` is a committed artefact and `frontend/src/lib/api/schema.d.ts` is generated
from it. That means a mistake here does not fail here — it fails in the frontend's typecheck,
often in a file nobody touched, with a message about a property that "does not exist" on a type
150 members long. These tests move that failure back to where it was caused.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

#: The committed contract. Regenerated by `uv run python -m uboss.export_openapi`.
CONTRACT = Path(__file__).resolve().parents[2] / "backend" / "openapi.json"

#: FastAPI's own name for the model it synthesises for `Body(embed=True)` parameters. Generated,
#: not authored, and not a collision.
GENERATED_PREFIX = "Body_"


@pytest.fixture(scope="module")
def contract() -> dict[str, object]:
    assert CONTRACT.exists(), f"{CONTRACT} is missing. Regenerate it."
    return json.loads(CONTRACT.read_text(encoding="utf-8"))


def test_the_contract_has_no_fully_qualified_schema_names(
    contract: dict[str, object],
) -> None:
    """Two Python classes sharing a name break the frontend, and not where you would look.

    FastAPI names an OpenAPI component after the class. When two modules both define, say,
    `PublishSummary`, the generator falls back to the full module path **on both of them** — so the
    new module's collision renames the *existing* one, and whichever frontend alias pointed at it
    stops compiling.

    It happened twice while Gate 5 was being built: `Visibility` against the Objective's, then
    `PublishSummary` and `WarningRead` against the Objective's publish schemas. Both times the
    first sign was a TypeScript error in a file nobody had edited.
    """
    schemas = contract["components"]["schemas"]  # type: ignore[index]
    qualified = sorted(
        name
        for name in schemas
        if "__" in name and not name.startswith(GENERATED_PREFIX)
    )
    assert not qualified, (
        "These schema names collided with another module's and were fully qualified by the "
        f"generator: {qualified}. Rename the newer class — a name like `AgentPublishSummary` "
        "rather than `PublishSummary`."
    )


def test_every_mutating_route_requires_an_idempotency_key(
    contract: dict[str, object],
) -> None:
    """CLAUDE.md: every mutating `/v1` request carries `Idempotency-Key`.

    A retry that reused a key must not act twice, and a route that never asked for one cannot
    tell a retry from a second request.
    """
    paths = contract["paths"]  # type: ignore[index]
    missing: list[str] = []
    for path, operations in paths.items():
        for method, operation in operations.items():
            if method.lower() not in ("post", "put", "patch", "delete"):
                continue
            headers = {
                parameter.get("name")
                for parameter in operation.get("parameters", [])
                if parameter.get("in") == "header"
            }
            if "Idempotency-Key" not in headers:
                missing.append(f"{method.upper()} {path}")

    #  The four session routes are the exceptions, and they are exceptions for one reason: a
    #  session is established by presenting credentials, and an idempotency key that replayed the
    #  stored response would hand somebody back a session they did not just authenticate for.
    #  Listed exactly rather than matched on a prefix, so a fifth auth route added later fails
    #  here and has to be argued for.
    allowed = {
        "POST /api/v1/auth/sign-in",
        "POST /api/v1/auth/sign-out",
        "POST /api/v1/auth/select-workspace",
        "POST /api/v1/auth/step-up/password",
    }
    unexpected = sorted(set(missing) - allowed)
    assert not unexpected, f"mutating routes with no Idempotency-Key header: {unexpected}"


def test_the_error_envelope_is_part_of_the_contract(
    contract: dict[str, object],
) -> None:
    """The frontend should not keep a hand-written copy of what a failure looks like."""
    schemas = contract["components"]["schemas"]  # type: ignore[index]
    assert "ErrorEnvelope" in schemas
